version: 0.2

env:
  git-credential-helper: yes
  variables:
    REPO: my-repo
    BRANCH: release

phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:
      - pip install git-remote-codecommit

      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

  pre_build:
    commands:
      # Check Go version
      - go version

      # Clone repo
      - git clone codecommit://${REPO} ${REPO}

      # Change and view directory
      - cd ${REPO}
      - ls -l

      # Fetch all dependencies
      - go get -t ./...

      # Check the Go code for common problems with 'go vet'
      - go vet

      # Run all tests included with our application
      - go test ./... -v

  build:
    commands:
  post_build:
    commands:
      - echo Start post_build...
      - git config --global user.email ${BRANCH}
      - git config --global user.name "CodeBuild"
      - git checkout -b ${BRANCH}
      # - git add .
      # - git commit -m "Commit tests passed"
      - git tag v1.0 $(git rev-parse --short HEAD)
      - git status
      # - git merge main
      - git push origin ${BRANCH} --tags
